---
repos:
  - repo: local
    hooks:
      - id: yamllint
        name: yamllint
        entry: |
          .venv/bin/yamllint -c=.yamllint.yml .
        language: system
        types: [yaml]
        pass_filenames: false
      - id: ansible-lint
        name: ansible-lint
        entry: |
          .venv/bin/ansible-lint -c .ansible-lint
        language: system
        types: [yaml]
        pass_filenames: false
