---
# Based on ansible-lint config
extends: default

ignore:
  - .venv/
  - .ansible/

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  colons:
    max-spaces-after: -1
    level: error
  commas:
    max-spaces-after: -1
    level: error
  comments:
    min-spaces-from-content: 1
    level: error
  comments-indentation: false
  document-start:
    level: error
  empty-lines:
    max: 3
    level: error
  hyphens:
    level: error
  indentation:
    level: error
  key-duplicates:
    level: error
  line-length: {level: error, max: 180}
  new-line-at-end-of-file:
    level: error
  new-lines:
    type: unix
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  trailing-spaces:
    level: error
  truthy:
    level: error
