---
- name: Update all packages to the latest version
  become: true
  ansible.builtin.apt:  # noqa package-latest
    upgrade: dist
    state: latest
    update_cache: true

- name: Install a few additional packages
  ansible.builtin.apt:
    pkg:
      - rsyslog
