---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "ansible-paperless-ngx-${image:-systemd-ubuntu}-${tag:-20.04}"
    image: "${namespace:-jrei}/${image:-systemd-ubuntu}:${tag:-20.04}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    published_ports:
      - 8000:8000
    override_command: false
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  converge_sequence:
    - create
    - prepare
    - converge
    - destroy
  test_sequence:
    - create
    - prepare
    - verify
    - syntax
    - converge
    - verify
    - cleanup
    - destroy
  idempotence_sequence:
    - create
    - prepare
    - converge
    - idempotence
    - destroy