---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian11
    image: "geerlingguy/docker-debian11-ansible:latest"
    cgroupns_mode: host
    override_command: false
    dockerfile: ../Dockerfile.j2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: false
provisioner:
  name: ansible
  inventory:
    group_vars:
      # setting for the platform instance named 'instance'
      all:
        ansible_user: ansible
verifier:
  name: ansible
