---
name: Changelog Updating

"on":
  release:
    types: [released]

jobs:
  update_changelog:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: |
            CHANGELOG.md
          commit-message: 'docs(changelog): update changelog'
          title: 'docs(changelog): update changelog'
          body: Update changelog to reflect release changes
          branch: docs-changelog_update
          delete-branch: true
