---
name: Code Maintenance

"on":
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 5"  # At 07:00 on Friday

jobs:
  run_maintenance_tasks:
    name: Run check scripts
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Load environment vars
        id: dotenv
        uses: falti/dotenv-action@v1.1.3
        with:
          path: .github/workflows/env_vars.txt
          log-variables: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.dotenv.outputs.PYTHON_SETUP_VERSION }}

      - name: Upgrade pip
        run: |
          python3 -m pip install --constraint=.github/workflows/constraints.txt pip colorama
          python3 -m pip --version

      - run: |
          python3 maintenance/run_checks.py
