---
name: Label Creation

"on":
  push:
    branches:
      - master
    paths:
      - '.github/label_config.yml'
      - '.github/workflows/label_creation.yml'

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v4.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/label_config.yml
          dry-run: false
          skip-delete: false
